import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { AppError, FORBIDDEN, loadSessionContext, writeAudit } from "./actor";
import type { Db } from "./actor";
const schema=z.object({full_name:z.string().trim().min(2).max(120),document:z.string().trim().max(30).optional().nullable(),phone:z.string().trim().max(30).optional().nullable(),email:z.string().email().max(255).optional().nullable(),pix_key:z.string().trim().max(255).optional().nullable(),registered_at:z.string().optional().nullable(),status:z.enum(["ACTIVE","INACTIVE"]).default("ACTIVE"),notes:z.string().trim().max(4000).optional().nullable()});
const id=z.object({id:z.string().uuid()});
async function ctxFor(db:Db,userId:string,action:"VIEW"|"CREATE"|"EDIT"|"DELETE"){const ctx=await loadSessionContext(db,userId);if(!ctx.activeCompanyId||ctx.profile.status!=="ACTIVE"||ctx.company?.status!=="ACTIVE")throw FORBIDDEN();if(!(ctx.isCompanyAdmin||ctx.isNexusOwner||ctx.permissions.some(p=>p.module==="affiliates"&&p.action===action)))throw FORBIDDEN();return ctx;}
export const listAffiliates=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const ctx=await ctxFor(context.supabase,context.userId,"VIEW");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data,error}=await supabaseAdmin.from("affiliates").select("*").eq("company_id",ctx.activeCompanyId!).order("full_name");if(error)throw new AppError("LIST_FAILED","Não foi possível carregar os filiados.");return data??[];});
export const createAffiliate=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>schema.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"CREATE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:row,error}=await supabaseAdmin.from("affiliates").insert({...data,company_id:ctx.activeCompanyId!,registered_at:data.registered_at||undefined}).select("*").single();if(error||!row)throw new AppError("CREATE_FAILED","Não foi possível criar o filiado.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"AFFILIATE_CREATED",module:"affiliates",record_id:row.id,record_label:row.full_name,new_value:row});return row;});
export const updateAffiliate=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.merge(schema)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"EDIT");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("affiliates").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Filiado não encontrado.");const {id:affiliateId,...fields}=data;const {data:row,error}=await supabaseAdmin.from("affiliates").update({...fields,registered_at:fields.registered_at||before.registered_at}).eq("id",affiliateId).eq("company_id",ctx.activeCompanyId!).select("*").single();if(error||!row)throw new AppError("UPDATE_FAILED","Não foi possível atualizar o filiado.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"AFFILIATE_UPDATED",module:"affiliates",record_id:affiliateId,record_label:row.full_name,old_value:before,new_value:row});return row;});
export const deleteAffiliate=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"DELETE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("affiliates").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Filiado não encontrado.");const {error}=await supabaseAdmin.from("affiliates").delete().eq("id",data.id).eq("company_id",ctx.activeCompanyId!);if(error)throw new AppError("DELETE_FAILED","Não foi possível excluir o filiado.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"AFFILIATE_DELETED",module:"affiliates",record_id:data.id,record_label:before.full_name,old_value:before});return {ok:true};});
