import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { AppError, FORBIDDEN, loadSessionContext, writeAudit } from "./actor";
import type { Db } from "./actor";
const schema=z.object({affiliate_id:z.string().uuid(),contract_id:z.string().uuid().nullable().optional(),amount:z.number().min(0),status:z.enum(["PENDING","PAID","OVERDUE","CANCELLED"]).default("PENDING"),due_date:z.string().optional().nullable(),paid_at:z.string().optional().nullable(),notes:z.string().trim().max(4000).optional().nullable()});
const id=z.object({id:z.string().uuid()});

async function syncCommissionCash(supabaseAdmin:any,row:any,userId:string,companyId:string){
  const referenceType="commission_payments";
  const {data:existing}=await supabaseAdmin.from("cash_transactions").select("id").eq("company_id",companyId).eq("reference_type",referenceType).eq("reference_id",row.id).maybeSingle();
  if(row.status==="PAID"){
    const description="Comissão"+(row.notes?" - "+row.notes:"");
    const payload={company_id:companyId,type:"EXPENSE",category:"Comissões",description,amount:Number(row.amount),transaction_date:row.paid_at||new Date().toISOString().slice(0,10),status:"PAID",reference_type:referenceType,reference_id:row.id,user_id:userId};
    if(existing?.id) await supabaseAdmin.from("cash_transactions").update(payload).eq("id",existing.id).eq("company_id",companyId);
    else await supabaseAdmin.from("cash_transactions").insert(payload as any);
  }else if(existing?.id){
    await supabaseAdmin.from("cash_transactions").delete().eq("id",existing.id).eq("company_id",companyId);
  }
}
async function ctxFor(db:Db,userId:string,action:"VIEW"|"CREATE"|"EDIT"|"DELETE"){const ctx=await loadSessionContext(db,userId);if(!ctx.activeCompanyId||ctx.profile.status!=="ACTIVE"||ctx.company?.status!=="ACTIVE")throw FORBIDDEN();if(!(ctx.isCompanyAdmin||ctx.isNexusOwner||ctx.permissions.some(p=>p.module==="commissions"&&p.action===action)))throw FORBIDDEN();return ctx;}
export const listCommissionPayments=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const ctx=await ctxFor(context.supabase,context.userId,"VIEW");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data,error}=await supabaseAdmin.from("commission_payments").select("*, affiliates(full_name), contracts(title)").eq("company_id",ctx.activeCompanyId!).order("created_at",{ascending:false});if(error)throw new AppError("LIST_FAILED","Não foi possível carregar as comissões.");return data??[];});
export const createCommissionPayment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>schema.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"CREATE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:row,error}=await supabaseAdmin.from("commission_payments").insert({...data,company_id:ctx.activeCompanyId!,contract_id:data.contract_id||null,due_date:data.due_date||null,paid_at:data.paid_at||null} as any).select("*").single();if(error||!row)throw new AppError("CREATE_FAILED","Não foi possível registrar a comissão.");await syncCommissionCash(supabaseAdmin,row,context.userId,ctx.activeCompanyId!);await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"COMMISSION_CREATED",module:"commissions",record_id:row.id,record_label:"Comissão",new_value:row});return row;});
export const updateCommissionPayment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.merge(schema).parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"EDIT");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("commission_payments").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Comissão não encontrada.");await supabaseAdmin.from("cash_transactions").delete().eq("company_id",ctx.activeCompanyId!).eq("reference_type","commission_payments").eq("reference_id",data.id);const {id:paymentId,...fields}=data;const {data:row,error}=await supabaseAdmin.from("commission_payments").update({...fields,contract_id:fields.contract_id||null,due_date:fields.due_date||null,paid_at:fields.paid_at||null} as any).eq("id",paymentId).eq("company_id",ctx.activeCompanyId!).select("*").single();if(error||!row)throw new AppError("UPDATE_FAILED","Não foi possível atualizar a comissão.");await syncCommissionCash(supabaseAdmin,row,context.userId,ctx.activeCompanyId!);await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"COMMISSION_UPDATED",module:"commissions",record_id:paymentId,record_label:"Comissão",old_value:before,new_value:row});return row;});
export const deleteCommissionPayment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"DELETE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("commission_payments").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Comissão não encontrada.");const {error}=await supabaseAdmin.from("commission_payments").delete().eq("id",data.id).eq("company_id",ctx.activeCompanyId!);if(error)throw new AppError("DELETE_FAILED","Não foi possível excluir a comissão.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"COMMISSION_DELETED",module:"commissions",record_id:data.id,record_label:"Comissão",old_value:before});return {ok:true};});
