import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { AppError, FORBIDDEN, loadSessionContext, writeAudit } from "./actor";
import type { Db } from "./actor";

const base=z.object({customer_id:z.string().uuid().nullable().optional(),responsible_user_id:z.string().uuid().nullable().optional(),platform:z.string().trim().min(2).max(40),format:z.string().trim().min(2).max(40),title:z.string().trim().max(180).optional().nullable(),caption:z.string().trim().max(10000).optional().nullable(),media_url:z.string().url().max(2000).optional().nullable(),scheduled_at:z.string().datetime().optional().nullable(),published_at:z.string().datetime().optional().nullable(),status:z.string().trim().max(40).default("DRAFT"),notes:z.string().trim().max(4000).optional().nullable()});
const id=z.object({id:z.string().uuid()});
async function ctxFor(db:Db,userId:string,action:"VIEW"|"CREATE"|"EDIT"|"DELETE"){const ctx=await loadSessionContext(db,userId);if(!ctx.activeCompanyId||ctx.profile.status!=="ACTIVE"||ctx.company?.status!=="ACTIVE")throw FORBIDDEN();if(!(ctx.isCompanyAdmin||ctx.isNexusOwner||ctx.permissions.some(p=>p.module==="content"&&p.action===action)))throw FORBIDDEN();return ctx;}
export const listContent=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const ctx=await ctxFor(context.supabase,context.userId,"VIEW");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data,error}=await supabaseAdmin.from("content_items").select("*, customers(name)").eq("company_id",ctx.activeCompanyId!).order("scheduled_at",{ascending:true});if(error)throw new AppError("LIST_FAILED","Não foi possível carregar os conteúdos.");return data??[];});
export const createContent=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>base.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"CREATE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:row,error}=await supabaseAdmin.from("content_items").insert({...data,company_id:ctx.activeCompanyId!,customer_id:data.customer_id||null,responsible_user_id:data.responsible_user_id||null}).select("*").single();if(error||!row)throw new AppError("CREATE_FAILED","Não foi possível criar o conteúdo.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"CONTENT_CREATED",module:"content",record_id:row.id,record_label:row.title||row.format,new_value:row});return row;});
export const updateContent=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.merge(base)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"EDIT");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("content_items").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Conteúdo não encontrado.");const {id:contentId,...fields}=data;const {data:row,error}=await supabaseAdmin.from("content_items").update({...fields,customer_id:fields.customer_id||null,responsible_user_id:fields.responsible_user_id||null}).eq("id",contentId).eq("company_id",ctx.activeCompanyId!).select("*").single();if(error||!row)throw new AppError("UPDATE_FAILED","Não foi possível atualizar o conteúdo.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"CONTENT_UPDATED",module:"content",record_id:contentId,record_label:row.title||row.format,old_value:before,new_value:row});return row;});
export const deleteContent=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"DELETE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("content_items").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Conteúdo não encontrado.");const {error}=await supabaseAdmin.from("content_items").delete().eq("id",data.id).eq("company_id",ctx.activeCompanyId!);if(error)throw new AppError("DELETE_FAILED","Não foi possível excluir o conteúdo.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"CONTENT_DELETED",module:"content",record_id:data.id,record_label:before.title||before.format,old_value:before});return {ok:true};});
