import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { AppError, FORBIDDEN, loadSessionContext, writeAudit } from "./actor";
import type { Db } from "./actor";

const schema=z.object({customer_id:z.string().uuid().nullable().optional(),affiliate_id:z.string().uuid().nullable().optional(),title:z.string().trim().min(2).max(180),service:z.string().trim().max(180).optional().nullable(),start_date:z.string().optional().nullable(),end_date:z.string().optional().nullable(),monthly_value:z.number().min(0).default(0),commission_percent:z.number().min(0).max(100).default(0),notes:z.string().trim().max(4000).optional().nullable(),status:z.string().trim().max(40).default("ACTIVE")});
const idSchema=z.object({id:z.string().uuid()});
async function ctxFor(supabase:Db,userId:string,action:"VIEW"|"CREATE"|"EDIT"|"DELETE"){const ctx=await loadSessionContext(supabase,userId);if(!ctx.activeCompanyId||ctx.profile.status!=="ACTIVE"||ctx.company?.status!=="ACTIVE")throw FORBIDDEN();if(!(ctx.isCompanyAdmin||ctx.isNexusOwner||ctx.permissions.some(p=>p.module==="contracts"&&p.action===action)))throw FORBIDDEN();return ctx;}
export const listContracts=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const ctx=await ctxFor(context.supabase,context.userId,"VIEW");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data,error}=await supabaseAdmin.from("contracts").select("*, customers(name), affiliates(full_name)").eq("company_id",ctx.activeCompanyId!).order("created_at",{ascending:false});if(error)throw new AppError("LIST_FAILED","Não foi possível carregar os contratos.");return data??[];});
export const createContract=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>schema.parse(input)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"CREATE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const commissionValue=Number(data.monthly_value)*Number(data.commission_percent)/100;const {data:created,error}=await supabaseAdmin.from("contracts").insert({...data,company_id:ctx.activeCompanyId!,commission_value:commissionValue,customer_id:data.customer_id||null,affiliate_id:data.affiliate_id||null}).select("*").single();if(error||!created)throw new AppError("CREATE_FAILED","Não foi possível criar o contrato.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"CONTRACT_CREATED",module:"contracts",record_id:created.id,record_label:created.title,new_value:created});return created;});
export const deleteContract=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>idSchema.parse(input)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"DELETE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("contracts").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Contrato não encontrado.");const {error}=await supabaseAdmin.from("contracts").delete().eq("id",data.id).eq("company_id",ctx.activeCompanyId!);if(error)throw new AppError("DELETE_FAILED","Não foi possível excluir o contrato.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"CONTRACT_DELETED",module:"contracts",record_id:data.id,record_label:before.title,old_value:before});return {ok:true};});
