import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { AppError, FORBIDDEN, loadSessionContext, writeAudit } from "./actor";
import type { Db } from "./actor";
const schema=z.object({supplier_id:z.string().uuid().nullable().optional(),description:z.string().trim().min(2).max(180),amount:z.number().min(0),due_date:z.string().optional().nullable(),status:z.enum(["PENDING","PAID","OVERDUE","CANCELLED"]).default("PENDING"),notes:z.string().trim().max(4000).optional().nullable()});
const id=z.object({id:z.string().uuid()});
async function ctxFor(db:Db,userId:string,action:"VIEW"|"CREATE"|"EDIT"|"DELETE"){const ctx=await loadSessionContext(db,userId);if(!ctx.activeCompanyId||ctx.profile.status!=="ACTIVE"||ctx.company?.status!=="ACTIVE")throw FORBIDDEN();if(!(ctx.isCompanyAdmin||ctx.isNexusOwner||ctx.permissions.some(p=>p.module==="finance"&&p.action===action)))throw FORBIDDEN();return ctx;}
export const listPayables=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const ctx=await ctxFor(context.supabase,context.userId,"VIEW");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data,error}=await supabaseAdmin.from("accounts_payable").select("*, suppliers(name)").eq("company_id",ctx.activeCompanyId!).order("due_date",{ascending:true});if(error)throw new AppError("LIST_FAILED","Não foi possível carregar contas a pagar.");return data??[];});
export const createPayable=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>schema.parse(v)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"CREATE");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:row,error}=await supabaseAdmin.from("accounts_payable").insert({...data,company_id:ctx.activeCompanyId!,supplier_id:data.supplier_id||null,due_date:data.due_date||null}).select("*").single();if(error||!row)throw new AppError("CREATE_FAILED","Não foi possível criar a conta a pagar.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"PAYABLE_CREATED",module:"finance",record_id:row.id,record_label:row.description,new_value:row});return row;});
export const updatePayable=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>id.merge(schema)).handler(async({data,context})=>{const ctx=await ctxFor(context.supabase,context.userId,"EDIT");const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:before}=await supabaseAdmin.from("accounts_payable").select("*").eq("id",data.id).eq("company_id",ctx.activeCompanyId!).maybeSingle();if(!before)throw new AppError("NOT_FOUND","Conta a pagar não encontrada.");const {id:pid,...fields}=data;const {data:row,error}=await supabaseAdmin.from("accounts_payable").update({...fields,supplier_id:fields.supplier_id||null,due_date:fields.due_date||null}).eq("id",pid).eq("company_id",ctx.activeCompanyId!).select("*").single();if(error||!row)throw new AppError("UPDATE_FAILED","Não foi possível atualizar a conta.");await writeAudit(supabaseAdmin,{company_id:ctx.activeCompanyId,user_id:context.userId,user_email:ctx.profile.email,action:"PAYABLE_UPDATED",module:"finance",record_id:pid,record_label:row.description,old_value:before,new_value:row});return row;});
