import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CircleDollarSign, Clock3, CheckCircle2, AlertTriangle, type LucideIcon } from "lucide-react";
import { AppShell } from "@/components/nexus/AppShell";
import { listCommissionPayments } from "@/lib/commissions.functions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
export const Route=createFileRoute("/_authenticated/estudio/comissoes")({component:CommissionsPage});
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function CommissionsPage(){const metricCards:Array<[string,number,LucideIcon]>=[["Pendente",0,Clock3],["Pago",0,CheckCircle2],["Em atraso",0,AlertTriangle],["Total",0,CircleDollarSign]];const fn=useServerFn(listCommissionPayments);const q=useQuery({queryKey:["studio-commissions"],queryFn:()=>fn()});const rows=q.data??[];const sum=(s:string)=>rows.filter(x=>x.status===s).reduce((a,x)=>a+Number(x.amount||0),0);return <AppShell title="Comissões" description="Controle de comissões dos filiados"><div className="space-y-6"><div><h2 className="text-lg font-semibold">Comissões</h2><p className="text-sm text-muted-foreground">Acompanhe valores pendentes, pagos e em atraso.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metricCards.map(([l,_,I])=><Card key={String(l)}><CardContent className="p-5"><I className="size-4 text-muted-foreground"/><div className="mt-3 text-xl font-semibold">{money(l==="Pendente"?sum("PENDING"):l==="Pago"?sum("PAID"):l==="Em atraso"?sum("OVERDUE"):rows.reduce((a,x)=>a+Number(x.amount||0),0))}</div><div className="text-xs text-muted-foreground">{String(l)}</div></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="text-base">Histórico</CardTitle></CardHeader><CardContent>{q.isLoading?<p className="text-sm text-muted-foreground">Carregando...</p>:rows.length===0?<div className="py-10 text-center text-sm text-muted-foreground">Nenhuma comissão registrada.</div>:<div className="space-y-2">{rows.map(x=><div key={x.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-4"><div className="min-w-0 flex-1"><div className="font-medium">{x.affiliates?.full_name||"Filiado"}</div><div className="text-xs text-muted-foreground">{x.contracts?.title||"Sem contrato"}{x.due_date?" · vencimento "+new Date(x.due_date+"T00:00:00").toLocaleDateString("pt-BR"):""}</div></div><div className="text-right"><div className="font-semibold">{money(Number(x.amount||0))}</div><div className="text-xs text-muted-foreground">{x.status}</div></div></div>)}</div>}</CardContent></Card></div></AppShell>}
