import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BriefcaseBusiness, Mail, Phone, UserPlus } from "lucide-react";
import { AppShell } from "@/components/nexus/AppShell";
import { listAffiliates } from "@/lib/affiliates.functions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/_authenticated/estudio/filiados")({component:AffiliatesPage});
function AffiliatesPage(){const fn=useServerFn(listAffiliates);const q=useQuery({queryKey:["studio-affiliates"],queryFn:()=>fn()});const rows=q.data??[];const active=rows.filter(x=>x.status==="ACTIVE").length;return <AppShell title="Filiados" description="Parceiros comerciais e comissões do Estúdio Nexus"><div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Filiados</h2><p className="text-sm text-muted-foreground">Gerencie parceiros que indicam e fecham contratos.</p></div><Button><UserPlus className="mr-2 size-4"/>Novo filiado</Button></div><div className="grid gap-4 sm:grid-cols-2"><Card><CardContent className="p-5"><BriefcaseBusiness className="size-4 text-muted-foreground"/><div className="mt-3 text-2xl font-semibold">{rows.length}</div><div className="text-xs text-muted-foreground">Total de filiados</div></CardContent></Card><Card><CardContent className="p-5"><BriefcaseBusiness className="size-4 text-muted-foreground"/><div className="mt-3 text-2xl font-semibold">{active}</div><div className="text-xs text-muted-foreground">Ativos</div></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Parceiros cadastrados</CardTitle></CardHeader><CardContent>{q.isLoading?<p className="text-sm text-muted-foreground">Carregando...</p>:rows.length===0?<div className="py-10 text-center text-sm text-muted-foreground">Nenhum filiado cadastrado ainda.</div>:<div className="space-y-2">{rows.map(x=><div key={x.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-4"><div className="flex size-10 items-center justify-center rounded-full bg-secondary font-semibold">{x.full_name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="font-medium">{x.full_name}</div><div className="mt-1 flex flex-wrap gap-3 text-xs text-muted-foreground">{x.email&&<span className="flex items-center gap-1"><Mail className="size-3"/> {x.email}</span>}{x.phone&&<span className="flex items-center gap-1"><Phone className="size-3"/> {x.phone}</span>}</div></div><span className="rounded-full border px-2 py-1 text-[11px]">{x.status==="ACTIVE"?"Ativo":"Inativo"}</span></div>)}</div>}</CardContent></Card></div></AppShell>}
