import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowDownToLine, ArrowUpFromLine, CircleDollarSign, Clock3 } from "lucide-react";
import { AppShell } from "@/components/nexus/AppShell";
import { listReceivables } from "@/lib/finance.functions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
export const Route=createFileRoute("/_authenticated/estudio/financeiro")({component:FinancePage});
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function FinancePage(){const fn=useServerFn(listReceivables);const q=useQuery({queryKey:["studio-finance-receivables"],queryFn:()=>fn()});const rows=q.data??[];const pending=rows.filter(x=>x.status==="PENDING").reduce((a,x)=>a+Number(x.amount||0),0);const overdue=rows.filter(x=>x.status==="OVERDUE").reduce((a,x)=>a+Number(x.amount||0),0);const paid=rows.filter(x=>x.status==="PAID").reduce((a,x)=>a+Number(x.amount||0),0);return <AppShell title="Financeiro" description="Contas a receber e fluxo financeiro do Estúdio Nexus"><div className="space-y-6"><div><h2 className="text-lg font-semibold">Financeiro</h2><p className="text-sm text-muted-foreground">Controle de receitas, recebimentos e valores em aberto.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["A receber",pending,CircleDollarSign],["Em atraso",overdue,Clock3],["Recebido",paid,ArrowUpFromLine],["Lançamentos",rows.length,ArrowDownToLine]].map(([l,v,I])=><Card key={String(l)}><CardContent className="p-5"><I className="size-4 text-muted-foreground"/><div className="mt-3 text-xl font-semibold">{typeof v==="number"&&l!=="Lançamentos"?money(v):String(v)}</div><div className="text-xs text-muted-foreground">{String(l)}</div></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="text-base">Contas a receber</CardTitle></CardHeader><CardContent>{q.isLoading?<p className="text-sm text-muted-foreground">Carregando...</p>:rows.length===0?<div className="py-10 text-center text-sm text-muted-foreground">Nenhuma conta a receber cadastrada.</div>:<div className="space-y-2">{rows.map(x=><div key={x.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-4"><div className="min-w-0 flex-1"><div className="font-medium">{x.description}</div><div className="text-xs text-muted-foreground">{x.customers?.name||"Sem cliente"} · vencimento {new Date(x.due_date+"T00:00:00").toLocaleDateString("pt-BR")}</div></div><div className="text-right"><div className="font-semibold">{money(Number(x.amount||0))}</div><div className="text-xs text-muted-foreground">{x.status}</div></div></div>)}</div>}</CardContent></Card></div></AppShell>}
