/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAcessoBloqueadoRouteImport } from './routes/_authenticated/acesso-bloqueado'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedNexusIndexRouteImport } from './routes/_authenticated/nexus/index'
import { Route as AuthenticatedNexusAuditoriaRouteImport } from './routes/_authenticated/nexus/auditoria'
import { Route as AuthenticatedNexusConfiguracoesRouteImport } from './routes/_authenticated/nexus/configuracoes'
import { Route as AuthenticatedNexusUsuariosRouteImport } from './routes/_authenticated/nexus/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcessoBloqueadoRoute =
  AuthenticatedAcessoBloqueadoRouteImport.update({
    id: '/acesso-bloqueado',
    path: '/acesso-bloqueado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNexusIndexRoute = AuthenticatedNexusIndexRouteImport.update({
  id: '/nexus/',
  path: '/nexus/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNexusAuditoriaRoute =
  AuthenticatedNexusAuditoriaRouteImport.update({
    id: '/nexus/auditoria',
    path: '/nexus/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNexusConfiguracoesRoute =
  AuthenticatedNexusConfiguracoesRouteImport.update({
    id: '/nexus/configuracoes',
    path: '/nexus/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNexusUsuariosRoute =
  AuthenticatedNexusUsuariosRouteImport.update({
    id: '/nexus/usuarios',
    path: '/nexus/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acesso-bloqueado': typeof AuthenticatedAcessoBloqueadoRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/nexus/auditoria': typeof AuthenticatedNexusAuditoriaRoute
  '/nexus/configuracoes': typeof AuthenticatedNexusConfiguracoesRoute
  '/nexus/usuarios': typeof AuthenticatedNexusUsuariosRoute
  '/nexus/': typeof AuthenticatedNexusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acesso-bloqueado': typeof AuthenticatedAcessoBloqueadoRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/nexus/auditoria': typeof AuthenticatedNexusAuditoriaRoute
  '/nexus/configuracoes': typeof AuthenticatedNexusConfiguracoesRoute
  '/nexus/usuarios': typeof AuthenticatedNexusUsuariosRoute
  '/nexus': typeof AuthenticatedNexusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/acesso-bloqueado': typeof AuthenticatedAcessoBloqueadoRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/_authenticated/nexus/auditoria': typeof AuthenticatedNexusAuditoriaRoute
  '/_authenticated/nexus/configuracoes': typeof AuthenticatedNexusConfiguracoesRoute
  '/_authenticated/nexus/usuarios': typeof AuthenticatedNexusUsuariosRoute
  '/_authenticated/nexus/': typeof AuthenticatedNexusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acesso-bloqueado'
    | '/ajuda'
    | '/auditoria'
    | '/funcionarios'
    | '/painel'
    | '/trocar-senha'
    | '/nexus/auditoria'
    | '/nexus/configuracoes'
    | '/nexus/usuarios'
    | '/nexus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acesso-bloqueado'
    | '/ajuda'
    | '/auditoria'
    | '/funcionarios'
    | '/painel'
    | '/trocar-senha'
    | '/nexus/auditoria'
    | '/nexus/configuracoes'
    | '/nexus/usuarios'
    | '/nexus'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/acesso-bloqueado'
    | '/_authenticated/ajuda'
    | '/_authenticated/auditoria'
    | '/_authenticated/funcionarios'
    | '/_authenticated/painel'
    | '/_authenticated/trocar-senha'
    | '/_authenticated/nexus/auditoria'
    | '/_authenticated/nexus/configuracoes'
    | '/_authenticated/nexus/usuarios'
    | '/_authenticated/nexus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acesso-bloqueado': {
      id: '/_authenticated/acesso-bloqueado'
      path: '/acesso-bloqueado'
      fullPath: '/acesso-bloqueado'
      preLoaderRoute: typeof AuthenticatedAcessoBloqueadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nexus/': {
      id: '/_authenticated/nexus/'
      path: '/nexus'
      fullPath: '/nexus/'
      preLoaderRoute: typeof AuthenticatedNexusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nexus/auditoria': {
      id: '/_authenticated/nexus/auditoria'
      path: '/nexus/auditoria'
      fullPath: '/nexus/auditoria'
      preLoaderRoute: typeof AuthenticatedNexusAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nexus/configuracoes': {
      id: '/_authenticated/nexus/configuracoes'
      path: '/nexus/configuracoes'
      fullPath: '/nexus/configuracoes'
      preLoaderRoute: typeof AuthenticatedNexusConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nexus/usuarios': {
      id: '/_authenticated/nexus/usuarios'
      path: '/nexus/usuarios'
      fullPath: '/nexus/usuarios'
      preLoaderRoute: typeof AuthenticatedNexusUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessoBloqueadoRoute: typeof AuthenticatedAcessoBloqueadoRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedNexusAuditoriaRoute: typeof AuthenticatedNexusAuditoriaRoute
  AuthenticatedNexusConfiguracoesRoute: typeof AuthenticatedNexusConfiguracoesRoute
  AuthenticatedNexusUsuariosRoute: typeof AuthenticatedNexusUsuariosRoute
  AuthenticatedNexusIndexRoute: typeof AuthenticatedNexusIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessoBloqueadoRoute: AuthenticatedAcessoBloqueadoRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedNexusAuditoriaRoute: AuthenticatedNexusAuditoriaRoute,
  AuthenticatedNexusConfiguracoesRoute: AuthenticatedNexusConfiguracoesRoute,
  AuthenticatedNexusUsuariosRoute: AuthenticatedNexusUsuariosRoute,
  AuthenticatedNexusIndexRoute: AuthenticatedNexusIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
